[package]
name = "pointpca2-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32.5"
ordered-float = "4.0"
num-traits = "0.2.19"
libm = "0.2.8"
ply-rs = "0.1.3"
rayon = "1.10.0"
kd-tree = {version = "0.6.0", features = ["rayon"]}

[lib]
name = "pointpca2_rust"
path = "src/lib.rs"
